#!/bin/bash

# activates virtual envirenoment and exports variables in .env file

# IMPORTANT: MUST BE RUN LIKE SO `. ./_activate_environment` in order to receive
# environment variable

source .env
source ./$VENV_NAME/bin/activate
